export const mockUser = {
  id: '1',
  name: 'Sarah Johnson',
  email: 'sarah@example.com',
  avatar: '👩‍🍼',
}

export const mockGroups = [
  {
    id: '1',
    name: 'Postpartum Recovery Support',
    description: 'A safe space to share your postpartum journey and connect with other moms',
    topic: 'postpartum-recovery',
    members: [mockUser, { id: '2', name: 'Emily' }, { id: '3', name: 'Jessica' }],
    messageCount: 24,
  },
  {
    id: '2',
    name: 'Morning Yoga & Stretching',
    description: 'Gentle yoga and stretching exercises for postpartum bodies',
    topic: 'yoga',
    members: [mockUser, { id: '2', name: 'Emily' }],
    messageCount: 8,
  },
  {
    id: '3',
    name: 'New Parent Walk Club',
    description: 'Let\'s get out for fresh air! Meet up for walks with your little ones',
    topic: 'general',
    members: [mockUser, { id: '4', name: 'Michelle' }, { id: '5', name: 'Amanda' }],
    messageCount: 15,
  },
  {
    id: '4',
    name: 'Mental Health & Wellness',
    description: 'Discussion about postpartum depression, anxiety, and mental wellness',
    topic: 'mental-health',
    members: [mockUser, { id: '3', name: 'Jessica' }, { id: '6', name: 'Rachel' }],
    messageCount: 31,
  },
]

export const mockActivities = [
  {
    id: '1',
    title: 'Morning Yoga Class',
    description: 'Gentle postpartum yoga to strengthen your core and relax',
    type: 'yoga',
    date: '2024-07-08',
    time: '10:00 AM',
    location: 'Brooklyn Community Center',
    distanceKm: 2.4,
    duration: '1 hour',
    capacity: 15,
    participants: [mockUser, { id: '2', name: 'Emily' }, { id: '3', name: 'Jessica' }],
  },
  {
    id: '2',
    title: 'Perineum Strengthening Class',
    description: 'Specialized exercises to support postpartum recovery',
    type: 'exercise',
    date: '2024-07-09',
    time: '2:00 PM',
    location: 'Virtual',
    distanceKm: 0,
    duration: '45 minutes',
    capacity: 20,
    participants: [mockUser, { id: '4', name: 'Michelle' }],
  },
  {
    id: '3',
    title: 'Park Walk & Picnic',
    description: 'Casual walk in the park followed by a picnic. Bring your little ones!',
    type: 'walk',
    date: '2024-07-13',
    time: '9:30 AM',
    location: 'Central Park Entrance',
    distanceKm: 3.1,
    duration: '2 hours',
    capacity: 25,
    participants: [mockUser, { id: '2', name: 'Emily' }, { id: '5', name: 'Amanda' }, { id: '6', name: 'Rachel' }],
  },
  {
    id: '4',
    title: 'Postpartum Fitness Class',
    description: 'Low-impact exercises designed for postpartum bodies',
    type: 'exercise',
    date: '2024-07-10',
    time: '11:00 AM',
    location: 'Fitness Studio Downtown',
    distanceKm: 5.7,
    duration: '1 hour',
    capacity: 12,
    participants: [mockUser],
  },
]

export const mockHelpRequests = [
  {
    id: '1',
    title: 'Need help with meal prep',
    description: 'Looking for someone to help prepare a few meals for the week. I have ingredients ready.',
    type: 'meal',
    date: '2024-07-06',
    status: 'open',
    requestedBy: { id: '2', name: 'Emily' },
    helpOffers: [{ id: '1', name: 'Jessica' }],
  },
  {
    id: '2',
    title: 'Childcare help needed for Thursday',
    description: 'Need someone to watch my baby for 2 hours while I have a doctor appointment',
    type: 'childcare',
    date: '2024-07-11',
    status: 'open',
    requestedBy: { id: '3', name: 'Jessica' },
    helpOffers: [],
  },
  {
    id: '3',
    title: 'Help with cleaning',
    description: 'Looking for help with light cleaning around the house',
    type: 'cleaning',
    date: '2024-07-07',
    status: 'claimed',
    requestedBy: mockUser,
    helpOffers: [{ id: '2', name: 'Emily' }, { id: '4', name: 'Michelle' }],
  },
  {
    id: '4',
    title: 'Emotional support & coffee chat',
    description: 'Just need to talk to someone who understands. Miss adult conversation!',
    type: 'emotional',
    date: '2024-07-06',
    status: 'open',
    requestedBy: { id: '4', name: 'Michelle' },
    helpOffers: [{ id: '5', name: 'Amanda' }],
  },
]

export const mockBabysitters = [
  {
    id: '1',
    name: 'Lisa Chen',
    phone: '(555) 123-4567',
    bio: '10+ years of childcare experience. CPR & First Aid certified. Love working with infants and toddlers. References available!',
    rate: 18,
    experience: '10 years',
    verified: true,
  },
  {
    id: '2',
    name: 'Maria Rodriguez',
    phone: '(555) 234-5678',
    bio: 'Experienced nanny with a passion for child development. Great with babies. Available weekends and evenings.',
    rate: 16,
    experience: '7 years',
    verified: true,
  },
  {
    id: '3',
    name: 'Sophie Williams',
    phone: '(555) 345-6789',
    bio: 'College student studying early childhood education. Patient and fun! Perfect for playdates and light babysitting.',
    rate: 14,
    experience: '3 years',
    verified: false,
  },
]
